"""
Django settings for eagle_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r23*5*%lr266qd&z1s@5f!$b025r&zp1m$+6i5ah23s79m8rro'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dq_management',
    'django_snowflake',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eagle_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eagle_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'snowflake_dev': {
        'ENGINE': 'django_snowflake',
        'NAME': 'DEV_DB',
        'USER': 'dev_ds',
        'PASSWORD': 'Devds@2022',
        'HOST': 'marico-analytics',
        'ACCOUNT': 'marico-analytics',
        'WAREHOUSE': 'PRD_BI_COMPUTE_WHS',
        'SCHEMA': 'DATA_SCIENCE',
        'ROLE': 'DEV_DATA_SCIENTIST',
    },
    'snowflake_prod': {
        'ENGINE': 'django_snowflake',
        'NAME': 'PRD_DB',
        'USER': 'prod_ds',
        'PASSWORD': 'Ds@123',
        'HOST': 'marico-analytics',
        'ACCOUNT': 'marico-analytics',
        'WAREHOUSE': 'PRD_DATASCIENCE_REPORTING_WHS',
        'SCHEMA': 'PUBLIC',
        'ROLE': 'PRD_REPORTING_DATA_SCIENCE',
    }
}


EAGLE_DAGS_DIR = "/home/admaryant/Eagle_dq_project/dq_management/eagle_dags/"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


POWERBI_CREDENTIALS = {
    "type": "powerbi",
    "client_id": "dbdd98a4-a2b3-40a2-afec-3a6e412646dd",       
    "tenant_id": "5635d8b8-c9b9-4d9a-8a4d-f7cad74dc82a",
    "client_secret": "fgi8Q~nC3OOBxk2OF55UJhZ7-XRsKzk.DxNFzcJ-"
}
